const sets = {
    "Ecce Romani Chapter 34":{
        "modus":"-ī, m. way/method",
        "cūra":"-ae, f. care",
        "convīvium":"-ī, n. feast/banquet",
        "sal":"salis, m. salt/wit",
        "pessimus":"-a, -um, worst",
        "suāvis":"-is, -e, sweet/delightful",
        "vetus":"veteris, old",
        "foedus":"-a, -um, filthy/disgusting",
        "ēbrius":"-a, -um, drunk",
        "paucī":"-ae, -a, few",
        "merus":"-a, -um, pure",
        "creō":"creāre, creāvī, creātus, to appoint",
        "invocō":"-āre, -āvī, -ātus, to invoke/call upon",
        "poscō":"poscere, poposcī, to demand/ask for",
        "misceō":"miscēre, miscuī, mixtus, to mix",
        "sinō":"sinere, sīvī, situs, to allow",
        "hauriō":"haurīre, hausī, haustus, to drain",
        "placeō":"-ēre, -uī, (+dat) to please",
        "fīō":"fierī, factus sum, to become/be made/be done/happen",
        "dōnō":"-āre, -āvī, -ātus, to give",
        "et...et...":"both...and...",
        "quam":"than",
        "nimis":"too much",
        "nē...quidem":"not even",
        "paulātim":"gradually",
        "nīl":"nothing",
        "-ve":"or",
        "contrā":"in return"
    },
    "Ecce Romani Chapter 35":{
        "collis":"collis, gen. pl. collium, m. hill",
        "deus":"-ī, nom. pl. dī, m. god",
        "vulnus":"vulneris, n. wound",
        "fūstis":"fūstis, gen. pl. fūstium, m. club/cudgel",
        "timor":"timōris, m. fear",
        "tergum":"-ī, n. back",
        "sēcūrus":"-a, -um, carefree/free/unconcerned",
        "affectus":"-a, -um, overcome/affected",
        "prōnus":"-a, -um, face down",
        "summus":"-a, -um, greatest/very great/highest",
        "gravis":"-is, -e, heavy/serious",
        "dīligēns":"dīligentis, diligent, painstaking/thorough",
        "certus":"-a, -um, certain",
        "rēctus":"-a, -um, right/proper/straight",
        "ligō":"-āre, -āvī, -ātus, to bind up",
        "crēdō":"crēdere, crēdidī, crēditus, (+dat) to believe/trust",
        "percutiō":"percutere, percussī, percussus, to strike",
        "corripiō":"corripere, corripuī, correptus, to seize/grab",
        "adimō":"adimere, adēmī, adēmptus, to take away (from)",
        "quam":"than",
        "quam + superlative":"as...as possible",
        "cōnsecutī sunt":"they overtook"
    },
    "Ecce Romani Chapter 36":{
        "adulēscēns":"adulēscentis, m. youth, young man",
        "cōnsul":"cōnsulis, m. consul",
        "audāx":"audācis bold",
        "tristis":"-is, -e sad",
        "persuādeō":"persuādēre, persuāsī, persuāsus to persuade, make agreeable",
        "condō":"condere, condidī, conditus to found",
        "-que":"(enclitic conjunction) and",
        "hūc":"here/to here/hither",
        "prīdiē":"on the day before",
        "libenter":"gladly",
        "rūrsus":"again",
        "sānē":"certainly/of course",
        "morātus est":"he has stayed",
        "regressus est":"he has returned",
        "proficīscētur":"he will set out",
        "secūtī sunt":"they followed",
        "cōnātus est":"he tried"
    },
    "Ecce Romani Chapter 37":{
        "grammaticus":"-ī, m. secondary school teacher",
        "paedagōgus":"-ī, m. tutor",
        "pīstrīnum":"-ī, n. bakery",
        "scriblīta":"-ae, f. tart with cheese filling",
        "iēntāculum":"-ī, n. breakfast",
        "prāndium":"-ī, n. lunch",
        "paulum":"-ī, n. a small amount/a little",
        "magister":"magistrī, m. schoolmaster/teacher/captain",
        "ērudītus":"-a, -um, learned/scholarly",
        "ūtilis":"-is, -e, useful",
        "castīgō":"-āre, -āvī, -ātus, to rebuke/reprimand",
        "praeferō":"praeferre, praetulī, praelātus, to carry in front of",
        "cōnor":"cōnārī, cōnātus sum, to try",
        "moror":"morārī, morātus sum, to remain/stay/delay",
        "vereor":"verērī, verītus sum, to fear/be afraid",
        "collābor":"collābī, collāpsus sum, to collapse",
        "cōnsequor":"cōnsequī, cōnsecūtus sum, to overtake/catch up to",
        "loquor":"loquī, locūtus sum, to talk/speak",
        "proficīscor":"proficīscī, profectus sum, to set out/leave",
        "sequor":"sequī, secūtus sum, to follow",
        "ēgredior":"ēgredī, ēgressus sum, to go out/leave",
        "ingredior":"ingredī, ingressus sum, to go in/enter",
        "regredior":"regredī, regressus sum, to go back/return",
        "experior":"experīrī, expertus sum, to test/try",
        "cotīdiē":"daily/every day",
        "vel":"or",
        "etiamsī":"even if",
        "lūdus":"-ī, m. school"
    },
    "Ecce Romani Chapter 38":{
        "mēnsis":"mēnsis, m. month",
        "discipulus":"-ī, m. student",
        "annus":"-ī, m. year",
        "ruīna":"-ae, f. ruin/collapse",
        "terra":"-ae, f. earth/ground/land",
        "mare":"maris, n. sea",
        "tempestās":"tempestātis, f. storm",
        "nāvis":"nāvis, f. ship",
        "rēgīna":"-ae, f. queen",
        "aliquī":"-ae, -a, some",
        "Quotus":"-a, -um, ...? What...?",
        "coepit":"(he) began",
        "nāvigō":"-āre, -āvī, -ātus, to sail",
        "obsideō":"obsidēre, obsēdī, obsessus, to besiege",
        "incendō":"incendere, incendī, incēnsus, to burn/set on fire",
        "patior":"patī, passus sum, to suffer/endure",
        "dēleō":"dēlēre, dēlēvī, dēlētus, to destroy",
        "Quot...?":"How many...?"
    },
    "Ecce Romani Chapter 39 Part 1":{
        "verbum":"-ī, n word, verb",
        "comes":"comitis, m. companion",
        "deus":"-ī, m. god",
        "ferula":"-ae, f. cane",
        "domus":"-ūs, f. house",
        "rūs":"rūris, n. country/countryside",
        "bellum":"-ī, n. war",
        "hiems":"hiemis, f. winter",
        "oppidum":"-ī, n. town",
        "moneō":"-ēre, -uī, -itus, to advise/warn",
        "conticēscō":"conticēscere, conticuī, to become silent",
        "animadvertō":"animadvertere, animadvertī, animadversus, to notice",
        "pāreō":"-ēre, -uī, -itus, (+dat.) to obey",
        "extendō":"extendere, extendī, extentus, to hold out",
        "iactō":"-āre, -āvī, -ātus, to toss/buffet",
        "interest":"it is important",
        "idem ac":"the same as",
        "sīc":"thus, in this way",
        "antequam":"before",
        "nusquam":"nowhere",
        "trāns":"across",
        "Athēnae":"-ārum, f. pl. Athens",
        "Baiae":"-ārum, f. pl. Baiae",
        "Brundisium":"-ī, n. Brundisium",
        "Carthāgō":"Carthāginis, f. Carthage",
        "Dēlos":"Dēlī, f. Delos",
        "Gādēs":"Gādium, f. pl. Gades",
        "Philippī":"-ōrum, m. pl. Philippi",
        "Rōma":"-ae, f. Rome",
        "Sīdōn":"Sīdōnis, f. Sidon",
        "Aegyptus":"-ī, f. Egypt",
        "Āfrica":"-ae, f. Africa",
        "Gallia":"-ae, f. Gaul",
        "Hispānia":"-ae, f. Spain",
        "Italia":"-ae, f. Italy",
        "Thrācia":"-ae, f. Thrace"
    },
    "Ecce Romani Chapter 39 Part 2":{
        "fundus":"-ī, m. farm",
        "litterae":"-ārum, f. pl. letters/literature",
        "lingua":"-ae, f. tongue/language",
        "arma":"-ōrum, n. pl. arms/weapons",
        "ōra":"-ae, f. shore",
        "fātum":"-ī, n. fate",
        "lītus":"lītoris, n. shore",
        "altum":"-ī, n. the sea/the deep",
        "genus":"generis, n. race/stock/nation",
        "moenia":"moenium, n. pl. walls/city walls",
        "virīlis":"-is, -e, of manhood",
        "aeger":"aegra, aegrum, ill",
        "profugus":"-a, -um, exiled",
        "saevus":"-a, -um, savage",
        "memor":"memoris, remembering/mindful/unforgetting",
        "studeō":"-ēre, -uī, (+dat.) to study",
        "nāscor":"nāscī, nātus sum, to be born",
        "expellō":"expellere, expulī, expulsus, to drive out/expel",
        "vīvō":"vīvere, vīxī, vīctus, to live",
        "morior":"morī, mortuus sum, to die",
        "sepeliō":"sepelīre, sepelīvī, sepultus, to bury",
        "canō":"canere, cecinī, cantus, to sing",
        "abhinc":"ago/back from this point in time",
        "post":"after",
        "ante":"before",
        "ob":"on account of"
    },
    "Ecce Romani Chapter 40":{
        "scapha":"-ae, f. small boat/raft",
        "poena":"-ae, f. punishment",
        "crūdēlis":"-is, -e, cruel",
        "valeō":"-ēre, -uī, -itus, to be strong/be well",
        "natō":"-āre, -āvī, -ātus, to swim",
        "dēsiliō":"dēsilīre, dēsiluī, to leap down",
        "audeō":"audēre, ausus sum, to dare",
        "repellō":"repellere, reppulī, repulsus, to drive off/drive back/repel",
        "ignōrō":"-āre, -āvī, -ātus, to be ignorant/not to know",
        "obsecrō":"-āre, -āvī, -ātus, to beseech/beg",
        "discō":"discere, didicī, to learn",
        "cupiō":"cupere, cupīvī, cupītus, to desire/want",
        "rapiō":"rapere, rapuī, raptus, to seize/snatch",
        "arcessō":"arcessere, arcessīvī, arcessītus, to summon/send for",
        "gaudeō":"gaudēre, gāvīsus sum, to rejoice/be glad",
        "soleō":"solēre, solitus sum, to be accustomed to",
        "fīdō":"fīdere, fīsus sum, to confide in/trust",
        "fiō":"fierī, factus sum, to become/be made",
        "prīmō":"at first/first",
        "inde":"from there",
        "immō vērō":"on the contrary/in fact",
        "cum":"since, because/when",
        "cum prīmum":"as soon as",
        "quam prīmum":"as soon as possible"
    },
    "Ecce Romani Chapters 41-42":{
        "tēla":"-ae, f. web/fabric",
        "studium":"-ī, n. enthusiasm",
        "tālia":"tālium, n. pl. such things",
        "ventus":"-ī, m. wind",
        "unda":"-ae, f. wave",
        "magister":"magistrī, m. schoolmaster/master/captain",
        "casa":"-ae, f. hut/cottage",
        "pūgiō":"pūgiōnis, m. dagger",
        "dīves":"dīvitis, rich",
        "pauper":"pauperis, poor",
        "texō":"texere, texuī, textus, to weave",
        "coorior":"coorīrī, coortus sum, to rise up/arise",
        "ēvādō":"ēvādere, ēvāsī, ēvāsus, to escape",
        "adorior":"adorīrī, adortus sum, to attack",
        "resistō":"resistere, restitī, to resist",
        "superō":"-āre, -āvī, -ātus, to overcome",
        "convalēscō":"convalēscere, convaluī, to grow stronger/get well",
        "forās":"outside",
        "Quantum...!":"How much...!",
        "dīcitur":"(he) is said",
        "Prō dī immortālēs!":"Good Heavens!/On behalf of the immortal gods!",
        "clam":"secretly",
        "quoniam":"since"
    }
};