const months = [
    {
        "English":"January",
        "Acc.":"Iānūāriās",
        "Abl.":"Iānūāriīs",
        "length":31,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    },
    {
        "English":"February",
        "Acc.":"Februāriās",
        "Abl.":"Februāriīs",
        "length":28,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    },
    {
        "English":"March",
        "Acc.":"Mārtiās",
        "Abl.":"Mārtiīs",
        "length":31,
        "Kalends":1,
        "Nones":7,
        "Ides":15
    },
    {
        "English":"April",
        "Acc.":"Aprīlēs",
        "Abl.":"Aprīlibus",
        "length":30,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    },
    {
        "English":"May",
        "Acc.":"Māiās",
        "Abl.":"Māiīs",
        "length":31,
        "Kalends":1,
        "Nones":7,
        "Ides":15
    },
    {
        "English":"June",
        "Acc.":"Iūniās",
        "Abl.":"Iūniīs",
        "length":30,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    },
    {
        "English":"July",
        "Acc.":"Iūliās",
        "Abl.":"Iūliīs",
        "length":31,
        "Kalends":1,
        "Nones":7,
        "Ides":15
    },
    {
        "English":"August",
        "Acc.":"Augustās",
        "Abl.":"Augustīs",
        "length":31,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    },
    {
        "English":"September",
        "Acc.":"Septembrēs",
        "Abl.":"Septembribus",
        "length":30,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    },
    {
        "English":"October",
        "Acc.":"Octōbrēs",
        "Abl.":"Octōbribus",
        "length":31,
        "Kalends":1,
        "Nones":7,
        "Ides":15
    },
    {
        "English":"November",
        "Acc.":"Novembrēs",
        "Abl.":"Novembribus",
        "length":30,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    },
    {
        "English":"December",
        "Acc.":"Decembrēs",
        "Abl.":"Decembribus",
        "length":31,
        "Kalends":1,
        "Nones":5,
        "Ides":13
    }
];

const markers = {
    "Kalends":{
        "Acc.":"Kalendās",
        "Abl.":"Kalendīs"
    },
    "Nones":{
        "Acc.":"Nonās",
        "Abl.":"Nonīs"
    },
    "Ides":{
        "Acc.":"Īdūs",
        "Abl.":"Īdibus"
    }
};